//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "claim_leaves")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub cohort_address: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub claimant: String,
    pub entitlements: String,
    pub vault_index: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
