//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "compiled_vaults")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub vault_address: String,
    pub cohort_address: String,
    pub vault_index: i16,
    pub vault_budget_human: String,
    pub vault_budget_token: String,
    pub vault_dust_human: String,
    pub vault_dust_token: String,
    pub amount_per_entitlement_human: String,
    pub amount_per_entitlement_token: String,
    pub total_entitlements: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
