//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::campaign_csv_rows::Entity as CampaignCsvRows;
pub use super::campaigns::Entity as Campaigns;
pub use super::claim_leaves::Entity as ClaimLeaves;
pub use super::claim_proofs::Entity as ClaimProofs;
pub use super::cohorts::Entity as Cohorts;
pub use super::cohorts_csv_rows::Entity as CohortsCsvRows;
pub use super::vaults::Entity as Vaults;
