[features]
resolution = true
skip-lint = false

[programs.localnet]
prism_protocol = "B48CjFfcULXbB3xiw1oSQiKhpTY5SDgz9yVekgaVSAZt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "test-admin.json"

[scripts]
test = "cargo test-sbf"
