[features]
resolution = true
skip-lint = false

[programs.localnet]
prism_protocol = "PrsmV9Kh8HcJjPSShFidZFJrbWM5NWQ98ST8M2BNdAw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "secrets/decrypted-keypairs/localnet-deployer.json" # run ./scripts/decrypt-secrets to create this file

[scripts]
test = "cargo test-sbf"

[toolchain]
anchor_version = "0.31.1"  # `anchor-cli` version to use(requires `avm`)
solana_version = "2.1.21"  # Solana version to use(applies to all Solana tools)
