[features]
resolution = true
skip-lint = false

[programs.localnet]
prism_protocol = "PrsmV9Kh8HcJjPSShFidZFJrbWM5NWQ98ST8M2BNdAw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "secrets/decrypted-keypairs/localnet-deployer.json" # run ./scripts/decrypt-secrets to create this file

[scripts]
test = "cargo test-sbf"
