use clap::{Parser, Subcommand};
use solana_sdk::pubkey::Pubkey;
use std::path::PathBuf;

mod commands;
mod config;
mod error;

use error::CliResult;

#[derive(Parser)]
#[command(name = "prism-protocol")]
#[command(about = "Prism Protocol CLI - Efficient token distribution on Solana")]
#[command(version)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Generate test fixtures for benchmarking and development
    GenerateFixtures {
        /// Campaign name (will be slugified for directory structure)
        #[arg(long)]
        campaign_name: String,

        /// Base output directory for organized fixture structure
        #[arg(long, default_value = "test-artifacts/fixtures/")]
        output_dir: PathBuf,

        /// Number of claimants to generate
        #[arg(long, default_value = "1000")]
        count: u64,

        /// Distribution type
        #[arg(long, default_value = "uniform")]
        distribution: String,

        /// Minimum entitlements per claimant
        #[arg(long, default_value = "1")]
        min_entitlements: u64,

        /// Maximum entitlements per claimant
        #[arg(long, default_value = "100")]
        max_entitlements: u64,

        /// Number of cohorts to generate
        #[arg(long, default_value = "3")]
        cohort_count: usize,

        /// Minimum amount per entitlement (in token base units)
        #[arg(long, default_value = "1000000")]
        min_amount_per_entitlement: u64,

        /// Maximum amount per entitlement (in token base units)
        #[arg(long, default_value = "10000000")]
        max_amount_per_entitlement: u64,
    },

    /// Compile campaign from CSV files into deployment-ready database
    CompileCampaign {
        /// Input campaign CSV file path (cohort,claimant,entitlements)
        #[arg(long)]
        campaign_csv_in: PathBuf,

        /// Input cohorts CSV file path (cohort,amount_per_entitlement)
        #[arg(long)]
        cohorts_csv_in: PathBuf,

        /// SPL token mint that will be distributed
        #[arg(long)]
        mint: Pubkey,

        /// Path to admin keypair file
        #[arg(long)]
        admin_keypair: PathBuf,

        /// Maximum claimants per vault (affects rent costs, can be reclaimed)
        #[arg(long, default_value = "200000")]
        claimants_per_vault: usize,

        /// Output path for campaign database
        #[arg(long)]
        campaign_db_out: PathBuf,
    },

    /// Deploy campaign on-chain
    DeployCampaign {
        /// Campaign database file (generated by compile-campaign)
        #[arg(long)]
        campaign_db_in: PathBuf,

        /// Admin keypair file
        #[arg(long)]
        admin_keypair: PathBuf,

        /// Solana RPC URL
        #[arg(long, default_value = "http://127.0.0.1:8899")]
        rpc_url: String,
    },

    /// Pause a campaign
    PauseCampaign {
        /// Campaign fingerprint (hex string)
        campaign: String,

        /// Admin keypair file
        #[arg(short, long)]
        keypair: PathBuf,

        /// Solana RPC URL
        #[arg(short, long, default_value = "https://api.mainnet-beta.solana.com")]
        rpc_url: String,
    },

    /// Resume a campaign
    ResumeCampaign {
        /// Campaign fingerprint (hex string)
        campaign: String,

        /// Admin keypair file
        #[arg(short, long)]
        keypair: PathBuf,

        /// Solana RPC URL
        #[arg(short, long, default_value = "https://api.mainnet-beta.solana.com")]
        rpc_url: String,
    },

    /// Reclaim tokens from a cohort
    ReclaimTokens {
        /// Campaign fingerprint (hex string)
        campaign: String,

        /// Cohort merkle root (hex string)
        cohort: String,

        /// Admin keypair file
        #[arg(short, long)]
        keypair: PathBuf,

        /// Solana RPC URL
        #[arg(short, long, default_value = "https://api.mainnet-beta.solana.com")]
        rpc_url: String,
    },

    /// Get campaign status
    CampaignStatus {
        /// Campaign fingerprint (hex string)
        campaign: String,

        /// Solana RPC URL
        #[arg(short, long, default_value = "https://api.mainnet-beta.solana.com")]
        rpc_url: String,
    },
}

fn main() -> CliResult<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::GenerateFixtures {
            campaign_name,
            output_dir,
            count,
            distribution,
            min_entitlements,
            max_entitlements,
            cohort_count,
            min_amount_per_entitlement,
            max_amount_per_entitlement,
        } => commands::generate_fixtures::execute(
            campaign_name,
            output_dir,
            count,
            distribution,
            min_entitlements,
            max_entitlements,
            cohort_count,
            min_amount_per_entitlement,
            max_amount_per_entitlement,
        ),

        Commands::CompileCampaign {
            campaign_csv_in,
            cohorts_csv_in,
            mint,
            admin_keypair,
            claimants_per_vault,
            campaign_db_out,
        } => commands::compile_campaign::execute(
            campaign_csv_in,
            cohorts_csv_in,
            mint,
            admin_keypair,
            claimants_per_vault,
            campaign_db_out,
        ),

        Commands::DeployCampaign {
            campaign_db_in,
            admin_keypair,
            rpc_url,
        } => commands::deploy_campaign::execute(campaign_db_in, admin_keypair, rpc_url),

        Commands::PauseCampaign {
            campaign,
            keypair,
            rpc_url,
        } => commands::pause_campaign::execute(campaign, keypair, rpc_url),

        Commands::ResumeCampaign {
            campaign,
            keypair,
            rpc_url,
        } => commands::resume_campaign::execute(campaign, keypair, rpc_url),

        Commands::ReclaimTokens {
            campaign,
            cohort,
            keypair,
            rpc_url,
        } => commands::reclaim_tokens::execute(campaign, cohort, keypair, rpc_url),

        Commands::CampaignStatus { campaign, rpc_url } => {
            commands::campaign_status::execute(campaign, rpc_url)
        }
    }
}
