[package]
name = "prism-protocol-merkle"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = { workspace = true }
prism_protocol = { path = "../../programs/prism-protocol", features = [
    "no-entrypoint",
] }
rs_merkle = { workspace = true }
