[package]
name = "prism-protocol-testing"
version = "0.1.0"
edition = "2021"

[lib]
name = "prism_protocol_testing"
path = "src/lib.rs"

[dependencies]
prism-protocol-merkle = { path = "../prism-protocol-merkle" }
prism-protocol-sdk = { path = "../prism-protocol-sdk" }
prism_protocol = { path = "../../programs/prism-protocol" }

anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
mollusk-svm = { workspace = true }
mollusk-svm-programs-token = { workspace = true }
solana-program = { workspace = true }
solana-sdk = { workspace = true }
spl-token = { workspace = true }
